### ISSUE TITLE
Configurable fields for insert/update of salesforce lead

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/tc-connect2sf#22]
Right now we have to add fields into the code whenever we want to sync new fields from connect to salesforce. Purpose of this issue is to avoid the code changes for every new field being added/removed/updated to salesforce.

There are two ways that I and Ritesh came up with:

1. Store configuration of fields, to be added/updated to the salesforce, in salesforce itself as custom setting and then query that custom setting from tc-connect2sf to determine the fields to be copied to salesforce. Salesforce would also store the mapping between connect field and salesforce lead field.

2. Simply dump the details JSON in one new field `detailsJSON` in salesforce lead and than create a trigger in salesforce which would parse this JSON field and update the appropriate lead field from the parsed info.

For both approaches efforts would be about 1-2 week.

I am bit inclined towards 2.

fyi @vic-topcoder @mtwomey  @dmessing

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey @dmessing I have used second approach and instead of just saving the details JSON I have updated the integration code so that it now saves the complete JSON of the project in a text field (which would a hidden from layout) in Salesforce. I have also added trigger in Salesforce so that now parse that JSON on every insert/update and updates lead's Connect specific fields from that information. It would alleviate us from updating the code in this repo every time we have to add/remove a field to be synced to salesforce.

Changes are live in dev salesforce org and it is successfully updating the required fields. However, we might get few errors occasionally for some situations where lead update is triggered by some conditions other than usual update flows. I will monitor this in dev and if I get any exception/error, I would update the code accordingly.

Thanks @RiteshTC for helping me out with all Salesforce stuff.

**Comment by vikasrohit** [comment]
@vic-topcoder Change set prepared for deployment in salesforce. I would like to get it deployed as soon as possible so that in future we don't have to deploy tc-connect2sf for salesforce fields updates.

Will create PR to deploy this repo tomorrow.

**Comment by vic-topcoder** [comment]
@mtwomey - FYI. 

@vikasrohit - sounds like a good plan. Let's do it. Great job guys!

**Comment by vikasrohit** [comment]
@vic-topcoder Deployed to production. Thanks @RiteshTC for all help.
