### ISSUE TITLE
Company field is being updated with `Unkown` when the lead creates project in new reg flow

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/tc-connect2sf#29]
In new reg flow, when creates account in the first step, he/she fills the company name which we persist in Salesforce as well. However, as soon as the same user creates the new project, following the workflow, integration is updating the lead with `Company=Unkown`. It should not update the existing lead's Company details.

fyi @mtwomey @acshields @RishiRajSahu

**Comment by acshields** [comment]
awesome. thanks @vikasrohit !
