### ISSUE TITLE
Lead data is not captured when user enters only single name

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/tc-connect2sf#31]
When user does not enter the full name in the `First and last name` field in the new registration form, it fails to save the lead data in the salesforce. It is happening because all fields are marked as compulsory in the leadInfo endpoint

**Comment by vikasrohit** [comment]
@mtwomey @acshields patched on production, didn't get time to verify it today. Hopefully, it fixes the issue.

**Comment by acshields** [comment]
@vikasrohit - thanks!
